//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("NESTModel", "FK_ContentSectionContentBody", "ContentSections", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(NEST.Models.ContentSection), "ContentBodies", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(NEST.Models.ContentBody), true)]
[assembly: EdmRelationshipAttribute("NESTModel", "FK_ContentSectionContentType", "ContentTypes", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(NEST.Models.ContentType), "ContentSections", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(NEST.Models.ContentSection), true)]
[assembly: EdmRelationshipAttribute("NESTModel", "FK_Contributions_Registrants", "Registrants", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(NEST.Models.Registrant), "Contributions", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(NEST.Models.Contribution), true)]

#endregion

namespace NEST.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class NESTV1Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new NESTV1Entities object using the connection string found in the 'NESTV1Entities' section of the application configuration file.
        /// </summary>
        public NESTV1Entities() : base("name=NESTV1Entities", "NESTV1Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new NESTV1Entities object.
        /// </summary>
        public NESTV1Entities(string connectionString) : base(connectionString, "NESTV1Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new NESTV1Entities object.
        /// </summary>
        public NESTV1Entities(EntityConnection connection) : base(connection, "NESTV1Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Configuration> Configurations
        {
            get
            {
                if ((_Configurations == null))
                {
                    _Configurations = base.CreateObjectSet<Configuration>("Configurations");
                }
                return _Configurations;
            }
        }
        private ObjectSet<Configuration> _Configurations;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ContentBody> ContentBodies
        {
            get
            {
                if ((_ContentBodies == null))
                {
                    _ContentBodies = base.CreateObjectSet<ContentBody>("ContentBodies");
                }
                return _ContentBodies;
            }
        }
        private ObjectSet<ContentBody> _ContentBodies;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ContentSection> ContentSections
        {
            get
            {
                if ((_ContentSections == null))
                {
                    _ContentSections = base.CreateObjectSet<ContentSection>("ContentSections");
                }
                return _ContentSections;
            }
        }
        private ObjectSet<ContentSection> _ContentSections;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ContentType> ContentTypes
        {
            get
            {
                if ((_ContentTypes == null))
                {
                    _ContentTypes = base.CreateObjectSet<ContentType>("ContentTypes");
                }
                return _ContentTypes;
            }
        }
        private ObjectSet<ContentType> _ContentTypes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Contribution> Contributions
        {
            get
            {
                if ((_Contributions == null))
                {
                    _Contributions = base.CreateObjectSet<Contribution>("Contributions");
                }
                return _Contributions;
            }
        }
        private ObjectSet<Contribution> _Contributions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Registrant> Registrants
        {
            get
            {
                if ((_Registrants == null))
                {
                    _Registrants = base.CreateObjectSet<Registrant>("Registrants");
                }
                return _Registrants;
            }
        }
        private ObjectSet<Registrant> _Registrants;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PolyCon> PolyCons
        {
            get
            {
                if ((_PolyCons == null))
                {
                    _PolyCons = base.CreateObjectSet<PolyCon>("PolyCons");
                }
                return _PolyCons;
            }
        }
        private ObjectSet<PolyCon> _PolyCons;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Configurations EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToConfigurations(Configuration configuration)
        {
            base.AddObject("Configurations", configuration);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ContentBodies EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToContentBodies(ContentBody contentBody)
        {
            base.AddObject("ContentBodies", contentBody);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ContentSections EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToContentSections(ContentSection contentSection)
        {
            base.AddObject("ContentSections", contentSection);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ContentTypes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToContentTypes(ContentType contentType)
        {
            base.AddObject("ContentTypes", contentType);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Contributions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToContributions(Contribution contribution)
        {
            base.AddObject("Contributions", contribution);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Registrants EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRegistrants(Registrant registrant)
        {
            base.AddObject("Registrants", registrant);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PolyCons EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPolyCons(PolyCon polyCon)
        {
            base.AddObject("PolyCons", polyCon);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NESTModel", Name="Configuration")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Configuration : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Configuration object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="googleAnalytics_ID">Initial value of the GoogleAnalytics_ID property.</param>
        /// <param name="twitterHandle">Initial value of the TwitterHandle property.</param>
        /// <param name="facebookURL">Initial value of the FacebookURL property.</param>
        /// <param name="googlePlusURL">Initial value of the GooglePlusURL property.</param>
        /// <param name="contributionEngine">Initial value of the ContributionEngine property.</param>
        public static Configuration CreateConfiguration(global::System.Int32 id, global::System.String googleAnalytics_ID, global::System.String twitterHandle, global::System.String facebookURL, global::System.String googlePlusURL, global::System.String contributionEngine)
        {
            Configuration configuration = new Configuration();
            configuration.Id = id;
            configuration.GoogleAnalytics_ID = googleAnalytics_ID;
            configuration.TwitterHandle = twitterHandle;
            configuration.FacebookURL = facebookURL;
            configuration.GooglePlusURL = googlePlusURL;
            configuration.ContributionEngine = contributionEngine;
            return configuration;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String GoogleAnalytics_ID
        {
            get
            {
                return _GoogleAnalytics_ID;
            }
            set
            {
                OnGoogleAnalytics_IDChanging(value);
                ReportPropertyChanging("GoogleAnalytics_ID");
                _GoogleAnalytics_ID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("GoogleAnalytics_ID");
                OnGoogleAnalytics_IDChanged();
            }
        }
        private global::System.String _GoogleAnalytics_ID;
        partial void OnGoogleAnalytics_IDChanging(global::System.String value);
        partial void OnGoogleAnalytics_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TwitterHandle
        {
            get
            {
                return _TwitterHandle;
            }
            set
            {
                OnTwitterHandleChanging(value);
                ReportPropertyChanging("TwitterHandle");
                _TwitterHandle = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TwitterHandle");
                OnTwitterHandleChanged();
            }
        }
        private global::System.String _TwitterHandle;
        partial void OnTwitterHandleChanging(global::System.String value);
        partial void OnTwitterHandleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FacebookURL
        {
            get
            {
                return _FacebookURL;
            }
            set
            {
                OnFacebookURLChanging(value);
                ReportPropertyChanging("FacebookURL");
                _FacebookURL = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FacebookURL");
                OnFacebookURLChanged();
            }
        }
        private global::System.String _FacebookURL;
        partial void OnFacebookURLChanging(global::System.String value);
        partial void OnFacebookURLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String GooglePlusURL
        {
            get
            {
                return _GooglePlusURL;
            }
            set
            {
                OnGooglePlusURLChanging(value);
                ReportPropertyChanging("GooglePlusURL");
                _GooglePlusURL = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("GooglePlusURL");
                OnGooglePlusURLChanged();
            }
        }
        private global::System.String _GooglePlusURL;
        partial void OnGooglePlusURLChanging(global::System.String value);
        partial void OnGooglePlusURLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ContributionEngine
        {
            get
            {
                return _ContributionEngine;
            }
            set
            {
                OnContributionEngineChanging(value);
                ReportPropertyChanging("ContributionEngine");
                _ContributionEngine = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ContributionEngine");
                OnContributionEngineChanged();
            }
        }
        private global::System.String _ContributionEngine;
        partial void OnContributionEngineChanging(global::System.String value);
        partial void OnContributionEngineChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NESTModel", Name="ContentBody")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ContentBody : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ContentBody object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="bodyText">Initial value of the BodyText property.</param>
        /// <param name="contentSection_ID">Initial value of the ContentSection_ID property.</param>
        public static ContentBody CreateContentBody(global::System.Int32 id, global::System.String title, global::System.String bodyText, global::System.Int32 contentSection_ID)
        {
            ContentBody contentBody = new ContentBody();
            contentBody.Id = id;
            contentBody.Title = title;
            contentBody.BodyText = bodyText;
            contentBody.ContentSection_ID = contentSection_ID;
            return contentBody;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String BodyText
        {
            get
            {
                return _BodyText;
            }
            set
            {
                OnBodyTextChanging(value);
                ReportPropertyChanging("BodyText");
                _BodyText = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("BodyText");
                OnBodyTextChanged();
            }
        }
        private global::System.String _BodyText;
        partial void OnBodyTextChanging(global::System.String value);
        partial void OnBodyTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SubHeader
        {
            get
            {
                return _SubHeader;
            }
            set
            {
                OnSubHeaderChanging(value);
                ReportPropertyChanging("SubHeader");
                _SubHeader = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SubHeader");
                OnSubHeaderChanged();
            }
        }
        private global::System.String _SubHeader;
        partial void OnSubHeaderChanging(global::System.String value);
        partial void OnSubHeaderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Promote
        {
            get
            {
                return _Promote;
            }
            set
            {
                OnPromoteChanging(value);
                ReportPropertyChanging("Promote");
                _Promote = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Promote");
                OnPromoteChanged();
            }
        }
        private global::System.String _Promote;
        partial void OnPromoteChanging(global::System.String value);
        partial void OnPromoteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CreationDate
        {
            get
            {
                return _CreationDate;
            }
            set
            {
                OnCreationDateChanging(value);
                ReportPropertyChanging("CreationDate");
                _CreationDate = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CreationDate");
                OnCreationDateChanged();
            }
        }
        private global::System.String _CreationDate;
        partial void OnCreationDateChanging(global::System.String value);
        partial void OnCreationDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Owner
        {
            get
            {
                return _Owner;
            }
            set
            {
                OnOwnerChanging(value);
                ReportPropertyChanging("Owner");
                _Owner = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Owner");
                OnOwnerChanged();
            }
        }
        private global::System.String _Owner;
        partial void OnOwnerChanging(global::System.String value);
        partial void OnOwnerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ContentSection_ID
        {
            get
            {
                return _ContentSection_ID;
            }
            set
            {
                OnContentSection_IDChanging(value);
                ReportPropertyChanging("ContentSection_ID");
                _ContentSection_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ContentSection_ID");
                OnContentSection_IDChanged();
            }
        }
        private global::System.Int32 _ContentSection_ID;
        partial void OnContentSection_IDChanging(global::System.Int32 value);
        partial void OnContentSection_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SortOrder
        {
            get
            {
                return _SortOrder;
            }
            set
            {
                OnSortOrderChanging(value);
                ReportPropertyChanging("SortOrder");
                _SortOrder = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SortOrder");
                OnSortOrderChanged();
            }
        }
        private Nullable<global::System.Int32> _SortOrder;
        partial void OnSortOrderChanging(Nullable<global::System.Int32> value);
        partial void OnSortOrderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Icon
        {
            get
            {
                return _Icon;
            }
            set
            {
                OnIconChanging(value);
                ReportPropertyChanging("Icon");
                _Icon = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Icon");
                OnIconChanged();
            }
        }
        private global::System.String _Icon;
        partial void OnIconChanging(global::System.String value);
        partial void OnIconChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SEOUrl
        {
            get
            {
                return _SEOUrl;
            }
            set
            {
                OnSEOUrlChanging(value);
                ReportPropertyChanging("SEOUrl");
                _SEOUrl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SEOUrl");
                OnSEOUrlChanged();
            }
        }
        private global::System.String _SEOUrl;
        partial void OnSEOUrlChanging(global::System.String value);
        partial void OnSEOUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TeaserText
        {
            get
            {
                return _TeaserText;
            }
            set
            {
                OnTeaserTextChanging(value);
                ReportPropertyChanging("TeaserText");
                _TeaserText = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TeaserText");
                OnTeaserTextChanged();
            }
        }
        private global::System.String _TeaserText;
        partial void OnTeaserTextChanging(global::System.String value);
        partial void OnTeaserTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MediaSourceURL
        {
            get
            {
                return _MediaSourceURL;
            }
            set
            {
                OnMediaSourceURLChanging(value);
                ReportPropertyChanging("MediaSourceURL");
                _MediaSourceURL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MediaSourceURL");
                OnMediaSourceURLChanged();
            }
        }
        private global::System.String _MediaSourceURL;
        partial void OnMediaSourceURLChanging(global::System.String value);
        partial void OnMediaSourceURLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IFrameURL
        {
            get
            {
                return _IFrameURL;
            }
            set
            {
                OnIFrameURLChanging(value);
                ReportPropertyChanging("IFrameURL");
                _IFrameURL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IFrameURL");
                OnIFrameURLChanged();
            }
        }
        private global::System.String _IFrameURL;
        partial void OnIFrameURLChanging(global::System.String value);
        partial void OnIFrameURLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IncludePageHeader
        {
            get
            {
                return _IncludePageHeader;
            }
            set
            {
                OnIncludePageHeaderChanging(value);
                ReportPropertyChanging("IncludePageHeader");
                _IncludePageHeader = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IncludePageHeader");
                OnIncludePageHeaderChanged();
            }
        }
        private global::System.String _IncludePageHeader;
        partial void OnIncludePageHeaderChanging(global::System.String value);
        partial void OnIncludePageHeaderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TitleSize
        {
            get
            {
                return _TitleSize;
            }
            set
            {
                OnTitleSizeChanging(value);
                ReportPropertyChanging("TitleSize");
                _TitleSize = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TitleSize");
                OnTitleSizeChanged();
            }
        }
        private global::System.String _TitleSize;
        partial void OnTitleSizeChanging(global::System.String value);
        partial void OnTitleSizeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SubHeaderSize
        {
            get
            {
                return _SubHeaderSize;
            }
            set
            {
                OnSubHeaderSizeChanging(value);
                ReportPropertyChanging("SubHeaderSize");
                _SubHeaderSize = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SubHeaderSize");
                OnSubHeaderSizeChanged();
            }
        }
        private global::System.String _SubHeaderSize;
        partial void OnSubHeaderSizeChanging(global::System.String value);
        partial void OnSubHeaderSizeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NESTModel", "FK_ContentSectionContentBody", "ContentSections")]
        public ContentSection ContentSection
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ContentSection>("NESTModel.FK_ContentSectionContentBody", "ContentSections").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ContentSection>("NESTModel.FK_ContentSectionContentBody", "ContentSections").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ContentSection> ContentSectionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ContentSection>("NESTModel.FK_ContentSectionContentBody", "ContentSections");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ContentSection>("NESTModel.FK_ContentSectionContentBody", "ContentSections", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NESTModel", Name="ContentSection")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ContentSection : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ContentSection object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="header">Initial value of the Header property.</param>
        /// <param name="uRL">Initial value of the URL property.</param>
        /// <param name="creationDate">Initial value of the CreationDate property.</param>
        /// <param name="contentTypeId">Initial value of the ContentTypeId property.</param>
        public static ContentSection CreateContentSection(global::System.Int32 id, global::System.String header, global::System.String uRL, global::System.String creationDate, global::System.Int32 contentTypeId)
        {
            ContentSection contentSection = new ContentSection();
            contentSection.Id = id;
            contentSection.Header = header;
            contentSection.URL = uRL;
            contentSection.CreationDate = creationDate;
            contentSection.ContentTypeId = contentTypeId;
            return contentSection;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Header
        {
            get
            {
                return _Header;
            }
            set
            {
                OnHeaderChanging(value);
                ReportPropertyChanging("Header");
                _Header = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Header");
                OnHeaderChanged();
            }
        }
        private global::System.String _Header;
        partial void OnHeaderChanging(global::System.String value);
        partial void OnHeaderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String URL
        {
            get
            {
                return _URL;
            }
            set
            {
                OnURLChanging(value);
                ReportPropertyChanging("URL");
                _URL = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("URL");
                OnURLChanged();
            }
        }
        private global::System.String _URL;
        partial void OnURLChanging(global::System.String value);
        partial void OnURLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CreationDate
        {
            get
            {
                return _CreationDate;
            }
            set
            {
                OnCreationDateChanging(value);
                ReportPropertyChanging("CreationDate");
                _CreationDate = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CreationDate");
                OnCreationDateChanged();
            }
        }
        private global::System.String _CreationDate;
        partial void OnCreationDateChanging(global::System.String value);
        partial void OnCreationDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ContentTypeId
        {
            get
            {
                return _ContentTypeId;
            }
            set
            {
                OnContentTypeIdChanging(value);
                ReportPropertyChanging("ContentTypeId");
                _ContentTypeId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ContentTypeId");
                OnContentTypeIdChanged();
            }
        }
        private global::System.Int32 _ContentTypeId;
        partial void OnContentTypeIdChanging(global::System.Int32 value);
        partial void OnContentTypeIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NESTModel", "FK_ContentSectionContentBody", "ContentBodies")]
        public EntityCollection<ContentBody> ContentBodies
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ContentBody>("NESTModel.FK_ContentSectionContentBody", "ContentBodies");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ContentBody>("NESTModel.FK_ContentSectionContentBody", "ContentBodies", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NESTModel", "FK_ContentSectionContentType", "ContentTypes")]
        public ContentType ContentType
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ContentType>("NESTModel.FK_ContentSectionContentType", "ContentTypes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ContentType>("NESTModel.FK_ContentSectionContentType", "ContentTypes").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ContentType> ContentTypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ContentType>("NESTModel.FK_ContentSectionContentType", "ContentTypes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ContentType>("NESTModel.FK_ContentSectionContentType", "ContentTypes", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NESTModel", Name="ContentType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ContentType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ContentType object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="behavior">Initial value of the Behavior property.</param>
        public static ContentType CreateContentType(global::System.Int32 id, global::System.String description, global::System.String behavior)
        {
            ContentType contentType = new ContentType();
            contentType.Id = id;
            contentType.Description = description;
            contentType.Behavior = behavior;
            return contentType;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Behavior
        {
            get
            {
                return _Behavior;
            }
            set
            {
                OnBehaviorChanging(value);
                ReportPropertyChanging("Behavior");
                _Behavior = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Behavior");
                OnBehaviorChanged();
            }
        }
        private global::System.String _Behavior;
        partial void OnBehaviorChanging(global::System.String value);
        partial void OnBehaviorChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NESTModel", "FK_ContentSectionContentType", "ContentSections")]
        public EntityCollection<ContentSection> ContentSections
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ContentSection>("NESTModel.FK_ContentSectionContentType", "ContentSections");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ContentSection>("NESTModel.FK_ContentSectionContentType", "ContentSections", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NESTModel", Name="Contribution")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Contribution : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Contribution object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="amount">Initial value of the Amount property.</param>
        /// <param name="registrant_ID">Initial value of the Registrant_ID property.</param>
        public static Contribution CreateContribution(global::System.Int32 id, global::System.Decimal amount, global::System.Int32 registrant_ID)
        {
            Contribution contribution = new Contribution();
            contribution.Id = id;
            contribution.Amount = amount;
            contribution.Registrant_ID = registrant_ID;
            return contribution;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Amount
        {
            get
            {
                return _Amount;
            }
            set
            {
                OnAmountChanging(value);
                ReportPropertyChanging("Amount");
                _Amount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Amount");
                OnAmountChanged();
            }
        }
        private global::System.Decimal _Amount;
        partial void OnAmountChanging(global::System.Decimal value);
        partial void OnAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Registrant_ID
        {
            get
            {
                return _Registrant_ID;
            }
            set
            {
                OnRegistrant_IDChanging(value);
                ReportPropertyChanging("Registrant_ID");
                _Registrant_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Registrant_ID");
                OnRegistrant_IDChanged();
            }
        }
        private global::System.Int32 _Registrant_ID;
        partial void OnRegistrant_IDChanging(global::System.Int32 value);
        partial void OnRegistrant_IDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NESTModel", "FK_Contributions_Registrants", "Registrants")]
        public Registrant Registrant
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Registrant>("NESTModel.FK_Contributions_Registrants", "Registrants").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Registrant>("NESTModel.FK_Contributions_Registrants", "Registrants").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Registrant> RegistrantReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Registrant>("NESTModel.FK_Contributions_Registrants", "Registrants");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Registrant>("NESTModel.FK_Contributions_Registrants", "Registrants", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NESTModel", Name="PolyCon")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PolyCon : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PolyCon object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="availableToList">Initial value of the AvailableToList property.</param>
        public static PolyCon CreatePolyCon(global::System.Int32 id, global::System.Boolean availableToList)
        {
            PolyCon polyCon = new PolyCon();
            polyCon.Id = id;
            polyCon.AvailableToList = availableToList;
            return polyCon;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Position
        {
            get
            {
                return _Position;
            }
            set
            {
                OnPositionChanging(value);
                ReportPropertyChanging("Position");
                _Position = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Position");
                OnPositionChanged();
            }
        }
        private global::System.String _Position;
        partial void OnPositionChanging(global::System.String value);
        partial void OnPositionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean AvailableToList
        {
            get
            {
                return _AvailableToList;
            }
            set
            {
                OnAvailableToListChanging(value);
                ReportPropertyChanging("AvailableToList");
                _AvailableToList = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AvailableToList");
                OnAvailableToListChanged();
            }
        }
        private global::System.Boolean _AvailableToList;
        partial void OnAvailableToListChanging(global::System.Boolean value);
        partial void OnAvailableToListChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SortOrder
        {
            get
            {
                return _SortOrder;
            }
            set
            {
                OnSortOrderChanging(value);
                ReportPropertyChanging("SortOrder");
                _SortOrder = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SortOrder");
                OnSortOrderChanged();
            }
        }
        private Nullable<global::System.Int32> _SortOrder;
        partial void OnSortOrderChanging(Nullable<global::System.Int32> value);
        partial void OnSortOrderChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NESTModel", Name="Registrant")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Registrant : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Registrant object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="firstName">Initial value of the FirstName property.</param>
        /// <param name="lastName">Initial value of the LastName property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="zipCode">Initial value of the ZipCode property.</param>
        public static Registrant CreateRegistrant(global::System.Int32 id, global::System.String firstName, global::System.String lastName, global::System.String email, global::System.String zipCode)
        {
            Registrant registrant = new Registrant();
            registrant.Id = id;
            registrant.FirstName = firstName;
            registrant.LastName = lastName;
            registrant.Email = email;
            registrant.ZipCode = zipCode;
            return registrant;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MI
        {
            get
            {
                return _MI;
            }
            set
            {
                OnMIChanging(value);
                ReportPropertyChanging("MI");
                _MI = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MI");
                OnMIChanged();
            }
        }
        private global::System.String _MI;
        partial void OnMIChanging(global::System.String value);
        partial void OnMIChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Company
        {
            get
            {
                return _Company;
            }
            set
            {
                OnCompanyChanging(value);
                ReportPropertyChanging("Company");
                _Company = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Company");
                OnCompanyChanged();
            }
        }
        private global::System.String _Company;
        partial void OnCompanyChanging(global::System.String value);
        partial void OnCompanyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Occupation
        {
            get
            {
                return _Occupation;
            }
            set
            {
                OnOccupationChanging(value);
                ReportPropertyChanging("Occupation");
                _Occupation = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Occupation");
                OnOccupationChanged();
            }
        }
        private global::System.String _Occupation;
        partial void OnOccupationChanging(global::System.String value);
        partial void OnOccupationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HomePhone
        {
            get
            {
                return _HomePhone;
            }
            set
            {
                OnHomePhoneChanging(value);
                ReportPropertyChanging("HomePhone");
                _HomePhone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HomePhone");
                OnHomePhoneChanged();
            }
        }
        private global::System.String _HomePhone;
        partial void OnHomePhoneChanging(global::System.String value);
        partial void OnHomePhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CellPhone
        {
            get
            {
                return _CellPhone;
            }
            set
            {
                OnCellPhoneChanging(value);
                ReportPropertyChanging("CellPhone");
                _CellPhone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CellPhone");
                OnCellPhoneChanged();
            }
        }
        private global::System.String _CellPhone;
        partial void OnCellPhoneChanging(global::System.String value);
        partial void OnCellPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address1
        {
            get
            {
                return _Address1;
            }
            set
            {
                OnAddress1Changing(value);
                ReportPropertyChanging("Address1");
                _Address1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address1");
                OnAddress1Changed();
            }
        }
        private global::System.String _Address1;
        partial void OnAddress1Changing(global::System.String value);
        partial void OnAddress1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address2
        {
            get
            {
                return _Address2;
            }
            set
            {
                OnAddress2Changing(value);
                ReportPropertyChanging("Address2");
                _Address2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address2");
                OnAddress2Changed();
            }
        }
        private global::System.String _Address2;
        partial void OnAddress2Changing(global::System.String value);
        partial void OnAddress2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String State
        {
            get
            {
                return _State;
            }
            set
            {
                OnStateChanging(value);
                ReportPropertyChanging("State");
                _State = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("State");
                OnStateChanged();
            }
        }
        private global::System.String _State;
        partial void OnStateChanging(global::System.String value);
        partial void OnStateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ZipCode
        {
            get
            {
                return _ZipCode;
            }
            set
            {
                OnZipCodeChanging(value);
                ReportPropertyChanging("ZipCode");
                _ZipCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ZipCode");
                OnZipCodeChanged();
            }
        }
        private global::System.String _ZipCode;
        partial void OnZipCodeChanging(global::System.String value);
        partial void OnZipCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String WebsiteURL
        {
            get
            {
                return _WebsiteURL;
            }
            set
            {
                OnWebsiteURLChanging(value);
                ReportPropertyChanging("WebsiteURL");
                _WebsiteURL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("WebsiteURL");
                OnWebsiteURLChanged();
            }
        }
        private global::System.String _WebsiteURL;
        partial void OnWebsiteURLChanging(global::System.String value);
        partial void OnWebsiteURLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TwitterURL
        {
            get
            {
                return _TwitterURL;
            }
            set
            {
                OnTwitterURLChanging(value);
                ReportPropertyChanging("TwitterURL");
                _TwitterURL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TwitterURL");
                OnTwitterURLChanged();
            }
        }
        private global::System.String _TwitterURL;
        partial void OnTwitterURLChanging(global::System.String value);
        partial void OnTwitterURLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FacebookURL
        {
            get
            {
                return _FacebookURL;
            }
            set
            {
                OnFacebookURLChanging(value);
                ReportPropertyChanging("FacebookURL");
                _FacebookURL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FacebookURL");
                OnFacebookURLChanged();
            }
        }
        private global::System.String _FacebookURL;
        partial void OnFacebookURLChanging(global::System.String value);
        partial void OnFacebookURLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LinkedInURL
        {
            get
            {
                return _LinkedInURL;
            }
            set
            {
                OnLinkedInURLChanging(value);
                ReportPropertyChanging("LinkedInURL");
                _LinkedInURL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LinkedInURL");
                OnLinkedInURLChanged();
            }
        }
        private global::System.String _LinkedInURL;
        partial void OnLinkedInURLChanging(global::System.String value);
        partial void OnLinkedInURLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comments
        {
            get
            {
                return _Comments;
            }
            set
            {
                OnCommentsChanging(value);
                ReportPropertyChanging("Comments");
                _Comments = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Comments");
                OnCommentsChanged();
            }
        }
        private global::System.String _Comments;
        partial void OnCommentsChanging(global::System.String value);
        partial void OnCommentsChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NESTModel", "FK_Contributions_Registrants", "Contributions")]
        public EntityCollection<Contribution> Contributions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Contribution>("NESTModel.FK_Contributions_Registrants", "Contributions");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Contribution>("NESTModel.FK_Contributions_Registrants", "Contributions", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
